
let baseUrl = 'http://localhost:8080/api/'
let MLConstants = {

  actions: {

    //
    // BASIC CRUD ACTIONS

    // MOVIES CRUD
    ACTION_MOVIE_CREATE: 'ACTION_MOVIE_ADD',
    ACTION_MOVIE_DELETE: 'ACTION_MOVIE_DELETE',
    ACTION_MOVIE_READ: 'ACTION_MOVIE_READ',
    ACTION_MOVIE_UPDATE: 'ACTION_MOVIE_UPDATE',

    // LISTS CRUD
    ACTION_LIST_CREATE: 'ACTION_LIST_CREATE',
    ACTION_LIST_DELETE: 'ACTION_LIST_DELETE',
    ACTION_LIST_READ: 'ACTION_LIST_READ',
    ACTION_LISTS_READ: 'ACTION_LIST_READ',

    //
    // ADDITIONAL ACTIONS

    // MOVIES
    ACTION_MOVIE_DISPLAY_DETAILS: 'ACTION_MOVIE_DISPLAY_DETAILS',

    // LISTS
    ACTION_LIST_DELETE_CURRENT: 'ACTION_LIST_DELETE_CURRENT',
    ACTION_LIST_READ_PERSONAL: 'ACTION_LIST_READ_PERSONAL',
    ACTION_LIST_SHARE: 'ACTION_LIST_SHARE',
    ACTION_LIST_RENDER_CREATE: 'ACTION_LIST_RENDER_CREATE',
    ACTION_LIST_RENDER_LISTS: 'ACTION_LIST_RENDER_LISTS'

  },

  view: {
    VIEW_LIST_ALL: 'VIEW_LIST_ALL',
    VIEW_LIST_CREATE: 'VIEW_LIST_CREATE',
    VIEW_LIST_SHARE: 'VIEW_LIST_SHARE'
  },

  ws: {
    LIST:          baseUrl + 'movies/list/',
    LIST_ALL:      baseUrl + 'movies/lists/',
    LIST_PERSONAL: baseUrl + 'movies/list/personal',
    LIST_SHARE:    baseUrl + 'movies/list/share'
  }
}

export default MLConstants