
let YTPlayerConstants = {

  ACTION_PLAY_VIDEO: 'ACTION_PLAY_VIDEO',
  ACTION_SEARCH_VIDEOS: 'ACTION_SEARCH-VIDEOS',
  ACTION_STOP_AND_CLOSE_PLAYER: 'ACTION_STOP_VIDEO'
}

export default YTPlayerConstants
